update glide.lock

diff --git a/vendor/github.com/appcelerator/amp/swarm b/vendor/github.com/appcelerator/amp/swarm
--- a/vendor/github.com/appcelerator/amp/swarm
+++ b/vendor/github.com/appcelerator/amp/swarm
@@ -10,8 +10,9 @@
 set -euo pipefail
 # INFLUXDATA_VERSION should be the Major.minor version, e.g 0.13 or 1.0
 INFLUXDATA_VERSION=1.0
-KAFKA_VERSION=10.0.0.1
-ZOOKEEPER_VERSION=3.4.8
+KAFKA_VERSION=0.10.0.1
+ZOOKEEPER_VERSION=3.4.9
+ETCD_VERSION=3.0.10
 
 # please keep sorted
 IMAGES=(
@@ -21,14 +22,15 @@ IMAGES=(
   appcelerator/amp-ui:latest
   appcelerator/elasticsearch-amp:latest
   appcelerator/grafana:latest
-  appcelerator/haproxy:latest
+  appcelerator/haproxy:1.0.1
   appcelerator/influxdb:influxdb-${INFLUXDATA_VERSION}
   appcelerator/kafka:${KAFKA_VERSION}
   appcelerator/kapacitor:kapacitor-${INFLUXDATA_VERSION}
   appcelerator/telegraf:telegraf-${INFLUXDATA_VERSION}
   registry:2
   appcelerator/zookeeper:${ZOOKEEPER_VERSION}
-  quay.io/coreos/etcd:v3.0.9
+  appcelerator/etcd:${ETCD_VERSION}
+  appcelerator/pinger:latest
 )
 
 MINIMAGES=(
@@ -41,7 +43,8 @@ MINIMAGES=(
   appcelerator/telegraf:telegraf-${INFLUXDATA_VERSION}
   registry:2
   appcelerator/zookeeper:${ZOOKEEPER_VERSION}
-  quay.io/coreos/etcd:v3.0.9
+  appcelerator/etcd:${ETCD_VERSION}
+  appcelerator/pinger:latest
 )
 
 # please keep sorted
@@ -158,9 +161,9 @@ initswarm() {
   docker node inspect self > /dev/null 2>&1 || docker swarm inspect > /dev/null 2>&1 || (echo "> Initializing swarm" && docker swarm init)
 }
 
-# set up the amp-swarm overlay network
+# set up the amp-infra overlay network
 createnetwork() {
-  docker network ls | grep amp-swarm || (echo "> Creating overlay network 'amp-swarm'" && docker network create -d overlay amp-swarm)
+  docker network ls | grep amp-infra || (echo "> Creating overlay network 'amp-infra'" && docker network create -d overlay amp-infra)
   docker network ls | grep amp-public || (echo "> Creating overlay network 'amp-public'" && docker network create -d overlay amp-public)
 }
 
@@ -172,11 +175,43 @@ pullimages() {
   for i in ${images[@]}; do docker pull $i; done
 }
 
+removevolume() {
+  # remove Docker volumes for explicitly mounted containers
+  local service=$1
+  local loop=0
+  local retrytime=0.5
+  local maxretries=10
+  if [[ -z $service ]]; then
+    return 1
+  fi
+  local volumename=amp-$service
+  echo -n "deleting volume $volumename "
+  while docker volume ls --filter name=$volumename | grep -wq $volumename; do
+    echo -n "."
+    docker volume rm "$volumename" >/dev/null 2>&1 && echo "volume $volumename has been successfully deleted" || true
+    sleep $retrytime
+    (( loop++ ))
+    if [[ $loop -gt $maxretries ]]; then
+      echo "failed, ignore"
+      break
+    fi
+  done
+  if [[ $loop -eq 0 ]]; then
+    echo -e "\b, volume does not exist"
+  fi
+}
+
 removeservices() {
   stop=$(docker service ls -q --filter "label=io.amp.role=$ROLE")
   [[ ! -z ${stop[0]} ]] && echo "> Removing current infrastructure services..." && docker service rm $stop || true
   stop=$(docker service ls -q --filter "label=io.amp.role=user")
   [[ ! -z ${stop[0]} ]] && echo "> Removing current user services..." && docker service rm $stop || true
+  for s in etcd; do
+    removevolume $s || echo "unable to remove volumes from $s service"
+  done
+  #remove user network
+  stop=$(docker network ls -q --filter "label=io.amp.role=user")
+  [[ ! -z ${stop[0]} ]] && echo "> Removing current user networks..." && docker network rm $stop || true
 }
 
 # start the services on the swarm
@@ -185,7 +220,8 @@ removeservices() {
 # otherwise the default is to start all the services in the SERVICES array.
 startservices() {
   removeservices
-
+  #remove etcd volume
+  sleep 1 && docker volume ls -qf "name=amp-etcd" | xargs -I {} docker volume rm {}
   echo "> Starting services..."
   # default is to run all the services
   # check if --min was specified
@@ -209,19 +245,19 @@ ls() {
 
 monitor() {
   interval=${1:-5}
-  clear; while true; do tput cup 0 0; docker service ls; sleep $interval; done
+  while true; do tput cup 0 0; tput ed; docker service ls; sleep $interval; done
 }
 
 registry() { # Owner: freignat91
-  docker service create --network amp-swarm --name registry \
+  docker service create --network amp-infra --name registry \
   --label io.amp.role="infrastructure" \
-  --mount type=bind,source=$HOME/registry/data,target=/var/lib/registry \
+  --mount type=volume,source=amp-registry,target=/var/lib/registry \
   -p 5000:5000 \
   registry:2
 }
 
 amplifier() {
-  docker service create --with-registry-auth --network amp-swarm,amp-public --name amplifier \
+  docker service create --with-registry-auth --network amp-infra,amp-public --name amplifier \
     --label io.amp.role="infrastructure" \
     --constraint "node.role == manager" \
     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
@@ -229,7 +265,7 @@ amplifier() {
 }
 
 ampagent() { # Owner: freignat91
-  docker service create --with-registry-auth --network amp-swarm --name amp-agent \
+  docker service create --with-registry-auth --network amp-infra --name amp-agent \
     --mode global \
     --label io.amp.role="infrastructure" \
     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
@@ -238,13 +274,13 @@ ampagent() { # Owner: freignat91
 
 # DEPENDENCIES kafka
 amplogworker() { # Owner: bertrand-quenin
-  docker service create --with-registry-auth --network amp-swarm --name amp-log-worker \
+  docker service create --with-registry-auth --network amp-infra --name amp-log-worker \
     --label io.amp.role="infrastructure" \
     appcelerator/amp-log-worker:latest
 }
 
 ampui() { # Owner: freignat91
-  docker service create --with-registry-auth --network amp-swarm --name amp-ui \
+  docker service create --with-registry-auth --network amp-infra --name amp-ui \
     --label io.amp.role="infrastructure" \
     --constraint "node.role == manager" \
     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
@@ -252,26 +288,27 @@ ampui() { # Owner: freignat91
 }
 
 elasticsearch() { # Owner: bertrand-quenin
-  docker service create --with-registry-auth --network amp-swarm --name elasticsearch \
+  docker service create --with-registry-auth --network amp-infra --name elasticsearch \
     --label io.amp.role="infrastructure" \
     -p 9200:9200 \
     -p 9300:9300 \
     appcelerator/elasticsearch-amp:latest
 }
 
-etcd() { # Owner: subfuzion
-  docker service create --with-registry-auth --network amp-swarm --name etcd \
+etcd() { # Owner: ndegory
+  docker service create --with-registry-auth --network amp-infra --name etcd \
     --label io.amp.role="infrastructure" \
     -p 2379:2379 \
     -p 2380:2380 \
-    quay.io/coreos/etcd:v3.0.9 etcd \
+    --mount type=volume,source=amp-etcd,target=/data \
+    appcelerator/etcd:${ETCD_VERSION} \
       --name etcd \
       --listen-client-urls http://0.0.0.0:2379 \
       --advertise-client-urls http://etcd:2379
   }
 
 grafana() { # Owner: ndegory
-  docker service create --with-registry-auth --network amp-swarm --name grafana \
+  docker service create --with-registry-auth --network amp-infra --name grafana \
     --label io.amp.role="infrastructure" \
     -p 6001:3000 \
     -e INFLUXDB_HOST=influxdb \
@@ -282,7 +319,7 @@ grafana() { # Owner: ndegory
 }
 
 influxdb() { # Owner: ndegory
-  docker service create --with-registry-auth --network amp-swarm --name influxdb \
+  docker service create --with-registry-auth --network amp-infra --name influxdb \
     --label io.amp.role="infrastructure" \
     -p 8086:8086 \
     -p 8083:8083 \
@@ -294,7 +331,7 @@ influxdb() { # Owner: ndegory
 
 # DEPENDENCIES zookeepeer
 kafka() { # Owner: bertrand-quenin
-  docker service create --with-registry-auth --network amp-swarm --name kafka \
+  docker service create --with-registry-auth --network amp-infra --name kafka \
     --label io.amp.role="infrastructure" \
     -p 9092:9092 \
     -e ZOOKEEPER_CONNECT=zookeeper:2181 \
@@ -303,7 +340,7 @@ kafka() { # Owner: bertrand-quenin
 }
 
 kapacitor() { # Owner: ndegory
-  docker service create --with-registry-auth --network amp-swarm --name kapacitor \
+  docker service create --with-registry-auth --network amp-infra --name kapacitor \
     --label io.amp.role="infrastructure" \
     -e INFLUXDB_URL=http://influxdb:8086 \
     -e KAPACITOR_HOSTNAME=auto \
@@ -318,15 +355,15 @@ kapacitor() { # Owner: ndegory
 }
 
 haproxy() { # Owner: freignat91
-  docker service create --with-registry-auth --network amp-swarm,amp-public --name haproxy \
+  docker service create --with-registry-auth --network amp-infra,amp-public --name haproxy \
     --label io.amp.role="infrastructure" \
     -p 8080:8080 \
     -p 80:80 \
-    appcelerator/haproxy:latest
+    appcelerator/haproxy:1.0.1
 }
 
 telegrafagent() { # Owner: ndegory
-  docker service create --with-registry-auth --network amp-swarm --name telegraf-agent \
+  docker service create --with-registry-auth --network amp-infra --name telegraf-agent \
     --mode global \
     --label io.amp.role="infrastructure" \
     -e OUTPUT_INFLUXDB_ENABLED=true \
@@ -349,7 +386,7 @@ telegrafagent() { # Owner: ndegory
 }
 
 zookeeper() { # Owner: bertrand-quenin
-  docker service create --with-registry-auth --network amp-swarm --name zookeeper \
+  docker service create --with-registry-auth --network amp-infra --name zookeeper \
     --label io.amp.role="infrastructure" \
     -p 2181:2181 \
     -p 2888:2888 \
